#!/bin/bash

sudo add-apt-repository ppa:neovim-ppa/stable

sudo apt install openjdk-8-jdk nodejs neovim python-neovim \
                 python3-neovim fzf rlwrap silversearcher-ag \
                 curl ripgrep, rbenv, zlib1g-dev
