#!/bin/bash
# RC files

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

packages=( "ag" "ripgrep" "ant" "cmus" "coreutils" "cscope" \)
           "imagemagick" "boot-clj" "sbt" "maven" "ranger" "tree" "vim" "wget" \
           "zsh" "jq" "macvim" "ruby" "python" "go" "highlight"\
           "node" "npm" "reattach-to-user-namespace" "neovim" );

if [ "$(uname -s)" = 'Darwin' ]; then
  for p in "${packages[@]}"
    do
    :
    brew uninstall --force $p
  done
  brew uninstall gnuplot
fi

rm -f ~/.tmux.conf
rm -rf ~/.vim/
rm -rf ~/.vimrc
